// A types object to allow creating arbitrary actions objects in tests
// instead of calling an async action that would normally be called
// and for switch on in redux store reducers
module.exports = {
  INITIAL_APP_DATA: 'INITIAL_APP_DATA',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  FETCH_FIELDS_SUCCESS: 'FETCH_FIELDS_SUCCESS',
  FETCH_FIELD_GROUPS_SUCCESS: 'FETCH_FIELD_GROUPS_SUCCESS',
  INVERT_SIDEBAR_EXPANSION: 'INVERT_SIDEBAR_EXPANSION',
  CLOSE_SIDEBAR_EXPANSION: 'CLOSE_SIDEBAR_EXPANSION',
  CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
  DISMISS_NOTIFICATION: 'DISMISS_NOTIFICATION'
}
